version: 1.2
workflows:
   - subclass: CWL
     primaryDescriptorPath: /Dockstore.cwl
     latestTagAsDefault: true
   - subclass: CWL
     name: hello-world
     primaryDescriptorPath: /Dockstore.cwl
     latestTagAsDefault: true
