version: 1.2
workflows:
   - subclass: CWL
     primaryDescriptorPath: /Dockstore.cwl
     latestTagAsDefault: true
   - subclass: CWL
     name: hello-world
     primaryDescriptorPath: /Dockstore.cwl
     latestTagAsDefault: true
     authors:
       - name: Man without orcid
         email: test@gmail.com
         role: Not spy
         affiliation: I spy2
       - name: Man with orcid
         orcid: 00000-11111-00000
         email: test2@gmail.com
         role: Spy
         affiliation: I spy
